--SCENARIO: EMPLOYEE MANAGEMENT SYSTEM
--YOU ARE TASKED WITH CREATING AN EMPLOYEE MANAGEMENT SYSTEM FOR A FICTIONAL COMPANY, "TECH INNOVATIONS," WHICH FOCUSES ON MANAGING EMPLOYEE INFORMATION EFFICIENTLY. THE SYSTEM SHOULD ALLOW HR PERSONNEL TO PERFORM VARIOUS OPERATIONS RELATED TO EMPLOYEE DATA.
--REQUIREMENTS:

--1.DATABASE CREATION: SET UP A NEW DATABASE NAMED "TECHINNOVATIONSDB" TO STORE ALL EMPLOYEE-RELATED INFORMATION.
CREATE DATABASE TECHINNOVATIONSDB;

USE TECHINNOVATIONSDB;

--2.SCHEMA DEFINITION: CREATE A SCHEMA NAMED "HR" TO LOGICALLY GROUP ALL EMPLOYEE-RELATED TABLES AND DATA.

CREATE SCHEMA HR;

--3.TABLE CREATION:

--A)CREATE AN "EMPLOYEES" TABLE WITHIN THE "HR" SCHEMA. THIS TABLE SHOULD INCLUDE FIELDS 
--SUCH AS EMPLOYEE ID, FIRST NAME, LAST NAME, DATE OF BIRTH, HIRE DATE, SALARY, AND EMAIL.
--B)IMPLEMENT AN IDENTITY COLUMN FOR THE EMPLOYEE ID TO AUTOMATICALLY GENERATE UNIQUE IDS FOR NEW EMPLOYEES.

CREATE TABLE EMPLOYEES(
	EMPLOYEE_ID INT PRIMARY KEY IDENTITY(1,1),
	FIRST_NAME VARCHAR(15), 
	LAST_NAME VARCHAR(15),
	EMAIL VARCHAR(20),
	DOB DATE,
	HIRE_DATE DATE,
	SALARY DECIMAL
);

ALTER SCHEMA HR TRANSFER dbo.employees;

--DROP TABLE HR.EMPLOYEES;
SELECT * FROM HR.EMPLOYEES;

INSERT INTO HR.Employees(First_Name, Last_Name,Email, DOB, Hire_Date, Salary)VALUES
	('Md','Ghouse','ghouse@gmail.com','2001-10-23','2024-09-16',33500.00),
	('Md','Ali','mdalio@gmail.com','2000-09-23','2023-09-16',36500.00),
	('Md','Ikram','mdikram1@gmail.com','2000-07-05','2024-10-03',28500.00),
	('Sharooq','Khan','khan@gmail.com','1999-10-31','2023-02-18',45300.00),
	('Mahaboob','Basha','mahaboob@gmail.com','2000-05-12','2024-09-02',25000.00);
--4.SEQUENCE GENERATION: DEFINE A SEQUENCE THAT GENERATES UNIQUE IDENTIFICATION NUMBERS FOR NEW EMPLOYEE RECORDS.

CREATE SEQUENCE EmployeeSeq
START WITH 1
INCREMENT BY 1;


--5.ADDING COLUMNS: AS THE HR DEPARTMENT EXPANDS, IT REQUIRES TRACKING ADDITIONAL INFORMATION, SUCH AS JOB TITLE AND DEPARTMENT. 
--ADD THESE COLUMNS TO THE "EMPLOYEES" TABLE.
ALTER TABLE HR.EMPLOYEES
ADD JOB_TITLE Varchar(25),
	DEPARTMENT Varchar(25);

--6.DATA MODIFICATIONS:

--A)CHANGE THE DATA TYPE OF THE SALARY COLUMN TO ACCOMMODATE LARGER SALARIES AS THE COMPANY GROWS.

ALTER TABLE HR.EMPLOYEES
ALTER COLUMN Salary DECIMAL(15,2);

--B)DROP THE EMAIL COLUMN IF THE COMPANY DECIDES TO SWITCH TO A DIFFERENT COMMUNICATION METHOD.

ALTER TABLE HR.EMPLOYEES
DROP COLUMN EMAIL;

--7.COMPUTED COLUMNS: INTRODUCE A COMPUTED COLUMN TO DISPLAY THE FULL NAME OF EACH EMPLOYEE BY COMBINING THE FIRST NAME AND LAST NAME FIELDS.

ALTER TABLE HR.EMPLOYEES
ADD FULLNAME AS (first_name+' '+last_name);

--8.DATA MANAGEMENT:

--A)TRUNCATE THE "EMPLOYEES" TABLE BEFORE PERFORMING A LARGE DATA IMPORT TO REMOVE ALL EXISTING RECORDS EFFICIENTLY.

TRUNCATE TABLE HR.Employees;

--B)DROP THE ENTIRE "EMPLOYEES" TABLE WHEN THE COMPANY DECIDES TO REDESIGN ITS EMPLOYEE DATA STRUCTURE.
--DROP TABLE HR.Employees;

--9.SCHEMA MANAGEMENT: IF THERE’S A NEED TO REORGANIZE DATA, TRANSFER THE "EMPLOYEES" TABLE TO A NEW SCHEMA NAMED "STAFF."
CREATE SCHEMA STAFF;

ALTER SCHEMA STAFF TRANSFER HR.EMPLOYEES;

SELECT * FROM STAFF.EMPLOYEES;
--TRUNCATE TABLE STAFF.EMPLOYEES;
INSERT INTO Staff.Employees (First_Name, Last_Name, DOB, Hire_Date, Salary, Job_Title, Department)
VALUES 
    ('John', 'Doe', '1985-03-15', '2022-01-10', 60000.00, 'Software Engineer', 'Development'),
    ('Jane', 'Smith', '1990-07-22', '2023-03-20', 65000.00, 'Project Manager', 'Management'),
    ('Emily', 'Johnson', '1988-12-05', '2021-05-15', 58000.00, 'QA Analyst', 'Quality Assurance'),
    ('Michael', 'Williams', '1992-01-30', '2020-08-01', 70000.00, 'DevOps Engineer', 'Infrastructure'),
    ('Jessica', 'Jones', '1983-04-12', '2023-02-14', 72000.00, 'Product Owner', 'Product Management'),
    ('David', 'Brown', '1995-09-18', '2023-04-25', 55000.00, 'Business Analyst', 'Business Analysis'),
    ('Sarah', 'Davis', '1986-10-10', '2022-11-05', 62000.00, 'UI/UX Designer', 'Design'),
    ('Daniel', 'Garcia', '1993-08-08', '2023-06-10', 48000.00, 'Support Specialist', 'Customer Support'),
    ('Laura', 'Martinez', '1991-02-20', '2022-09-01', 53000.00, 'Marketing Specialist', 'Marketing'),
    ('James', 'Hernandez', '1989-11-25', '2021-12-12', 75000.00, 'Data Scientist', 'Data Science');


--10.DATABASE DELETION: WHEN THE PROJECT IS COMPLETE AND NO LONGER NEEDED, DELETE THE ENTIRE "TECHINNOVATIONSDB" DATABASE TO FREE UP RESOURCES.

DROP DATABASE TECHINNOVATIONSDB;


